config/routes.rb
Unburyme::Application.routes.draw do
  get '/' => 'users#index'
  resources :users
  match '/sessions/create' => 'sessions#create'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'users#index'
  match 'logout' => 'sessions#destroy', via: [:get, :delete], as: :logout
  match ':controller(/:action(/:id(.:format)))'

  root :to => 'users#index'
end

app/models/user.rb
class User
  include Mongoid::Document

  field :name,     :type => String
  field :email,    :type => String
  field :provider, :type => String
  field :uid,      :type => String

  def update_info(auth)
    self.name = auth["info"]["nickname"] #twitter
    self.email = '' #twitter
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout Proc.new { |controller| controller.request.xhr? ? false : 'main' }

  private
  def current_user
    @current_user ||= logged_in? ? User.find(session[:user_id]) :nil
  end

  def logged_in?
    !!session[:user_id]
  end

  helper_method :current_user, :logged_in?, :log_in_notification
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_by(provider: auth["provider"], uid: auth["uid"])
    user.update_info(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "You are now logged in"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You have been logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/main.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Unbury Me Loan Calculator 
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    = ENV['UNBURYME_TWITTER_CONSUMER_KEY']
    / Navigation
    - if current_user
      = current_user.name
      = link_to "Log out", logout_path
    - else
      = link_to "Sign in with Twitter", "/auth/twitter"


    / Flash
    -if flash[:notice]
      .flash.notice 
        = flash[:notice]
    -if flash[:error]
      .flash.error
        = flash[:error]
    -if flash[:alert]
      .flash.alert
        = flash[:alert]


    / Content
    .container
      = yield

  %footer
    %p &copy; Company 2011
    / /container

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path